{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: ing-{{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - backend:
              serviceName: dhos-url-api-svc
              servicePort: 80
            path: /dhos-url(/|$)(.*)
{{- end }}
