apiVersion: v1
kind: Secret
metadata:
  name: dhos-url-api-secrets
  labels:
    app: dhos-url-api
data:
  DATABASE_PASSWORD: {{.Values.database.postgres_password | b64enc}}
  DATABASE_SU_PASSWORD: {{.Values.database.postgres_su_password | b64enc}}
