database:
    postgres_password: ENC[AES256_GCM,data:pIEtfLOvKLX0iBH7OtjfuGo6PLqzx/YhYhkDfPKjqVE=,iv:gUwSv1ZIuwDb4XKN/YAyzxL67MraNqC87ZxIdBb36U0=,tag:V7mHmGvdtIcnuqtx+39itw==,type:str]
    postgres_su_password: ENC[AES256_GCM,data:UR/9qAhfZAeKbmlK7NdI+cATtcOTGNPTMKfu1ZOpcrk=,iv:PzUnTGSAb/sKaOol7XPv6QMNs2Vap+Kgz/w0v7E/5YQ=,tag:9jRTOTkcfL5F1NMp+7ViYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://us-nonprod-keyvault.vault.azure.net
        name: dhos-url-api-sops
        version: 06005f7d89714b3fa13072a60e9191cc
        created_at: '2021-01-25T08:36:38Z'
        enc: B4jqOu2hFMHcMO36B6_zDX16b6nvQ-hVTWF83kkfCVt25rzDaUMB9ciSUQO_x-kxQFSrAiCSsj7g0wW8pszdaO9KUEVHY5F69fAnK_1y3bf50SNWkn2YUlrNQWEAFW8KLUQcty2-rLKS6uwatMzYMPVMxJ7bfX9__S_2PYvB-nDs5ztC4kXrggR83KFybflVjXpLCqjUrlLvTSTqfFX8b36dbbNVa16fWjGlkS8TioBbKkt83Wmgu3tSnIis2N2MFqLerPGu63wv2u9RQM7HXwDC8iO2OOSg69u9-T8SsgvIjk8TEBSQLqoXtR-9PwptNYTaUzNAj74e7g3Zpqrd1Q
    hc_vault: []
    lastmodified: '2021-01-25T08:36:44Z'
    mac: ENC[AES256_GCM,data:W/6kHRhyd+nnHkZcBjqsiNsSVBylLgy90OPns0AbwVnNFO/KgzRrc7oRj8pL60k88/+XzD15fnnYZqxFeQzDM1tfCaY0Hls6OqQzYbxZvYmMo4h5Pbuxb1HPDTBJd9lT4VH5rBkMBohiR0sZeT0C/G4+9LoKaSDXWWKDzSYNA1c=,iv:FykYYeUbyXWWdbJICnv7oPv/VCbITSqk7Zossm5NCrI=,tag:/2UKTP8H4jYjy0N5uaiwNA==,type:str]
    pgp:
    -   created_at: '2021-01-25T08:36:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf/W8Ky6+u9gXZ5HBIbjCo2JImAQCbPTi0sdjXIVyQyWl0M
            OLbE3swZHwGuyRMG8c373jysPHxrOyZ4/Fk2WOqUMZKYUgIgctn0SfL3dvoMb+MD
            rnV2DZWZKOFFTN9XZaM3HHBhqjlLlpDPnm8F1Tp38mGkj5Wuf2BSomrLqPRSEgS6
            3bNhztv+smwicj7Su2WrGDeFeMATsZAarm5EyET9RqZf8hLmkVWHp5utvILFRXQo
            V71ZAmpgJJPBIqaU5GOJzT9emMZOnySEbqBG+YIXMna6JLcN6267O4Gc1gyCvnhq
            2Cj9nTLQXz694YMnVDU66XQ7/HwmkJ6euaSe8bkgMNJeAQcW21H+mhMRu4fHR0mf
            QxGKNBTNo+Rvun99kwJbg789ktLZx4PtqlkboyUFtjczyHUds+VkPoz/M822s+aa
            b+Yf7JbPfQE/ndIv09o1PYTsFDMKRCQ1G7eSWAKMaw==
            =tc4Y
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.6.1
