database:
  dbhost: uk-prod006-hog-db.postgres.database.azure.com
  dbport: 5432
  db_user_name: dhos-url@uk-prod006-hog-db
  db_su_name: postgres@uk-prod006-hog-db
  db_name: dhos-url

imagePullPolicy: IfNotPresent
imagetag: r1.4.0

proxy_url: https://api-uk-prod.sensynehealth.com
environment: PRODUCTION

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /dhos-url
  hostName: api-prod.sensynehealth.local