database:
  dbhost: uk-nonprod-upstream-api001-shepherd-db.postgres.database.azure.com
  dbport: 5432
  db_user_name: dhos-url@uk-nonprod-upstream-api001-shepherd-db
  db_su_name: postgres@uk-nonprod-upstream-api001-shepherd-db
  db_name: dhos-url

proxy_url: https://api-uk-nonprod.sensynehealth.com
environment: NONPRODUCTION

imagePullPolicy: Always
imagetag: r1.11.0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-secret: 'dhos-mgmt/internal-mtls-cert'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '2'
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /dhos-url
  hostName: api-nonprod.sensynehealth.local
